### ISSUE TITLE
Wrong intersperse :)

### ISSUE THREAD

**Issue by anitasv** [mukeshtiwari/Isabelle#1]
https://github.com/mukeshtiwari/Isabelle/blob/fcb191b4c07f0f4dc121d9e0cc4d2bc5c8a5a50f/Chap2.thy#L146

```
(* Exercise 2.8 *)
fun intersperse  :: "'a ⇒ 'a list ⇒ 'a list" where
  "intersperse  a [] = []"|
  "intersperse  a [x1] = [x1]"|
  "intersperse  a (x1 # (x2 # xs)) = x1 # (a # (intersperse  a (x2 # xs)))"
```

**Comment by mukeshtiwari** [comment]
Hi Anita, Thank you very much.

**Comment by mukeshtiwari** [comment]
I don't think you need to destruct xs in third branch, but that is just matter of taste.
```
fun intersperse :: "'a \<Rightarrow> 'a list \<Rightarrow> 'a list" where
  "intersperse a [] = [a]"|
  "intersperse a [x] = [x]"|
  "intersperse a (x # xs) = x # a # intersperse a xs"
```

**Comment by anitasv** [comment]
true, but your first case is still wrong:
intersperse a [] = []

**Comment by mukeshtiwari** [comment]
Oops, I must have been sleeping while writing this code :). Thanks again @anitasv
