### ISSUE TITLE
I guess intent of the question was three cases Tip| Leaf|Node

### ISSUE THREAD

**Issue by anitasv** [mukeshtiwari/Isabelle#2]
https://github.com/mukeshtiwari/Isabelle/blob/fcb191b4c07f0f4dc121d9e0cc4d2bc5c8a5a50f/Chap2.thy#L126

Otherwise you can't construct something like: 
(BNode (BLeaf (3::nat)) 4 (BTip)

the reason was to illustrate use of rule: mirror2.induct

**Comment by mukeshtiwari** [comment]
Thank you. Please go through some more code and let me know what else I am missing.
